// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('HW_IDE', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('HW_IDE', async function() {
    await driver.get("http://testshop.sedtest-school.ru/")
    await driver.manage().window().setRect({ width: 810, height: 988 })
    await driver.findElement(By.linkText("Войти")).click()
    await driver.findElement(By.id("id_email")).click()
    await driver.findElement(By.id("id_email")).sendKeys("drugoyemeil@gmail.com")
    await driver.findElement(By.id("id_password")).click()
    await driver.findElement(By.id("id_password")).sendKeys("qwerty123")
    await driver.findElement(By.css(".btn")).click()
    assert(await driver.findElement(By.css(".card:nth-child(2) span:nth-child(1)")).getText() == "9.99 р")
    await driver.findElement(By.name("search")).click()
    await driver.findElement(By.name("search")).sendKeys("Ручка Паркер")
    await driver.findElement(By.name("search")).sendKeys("Ручка Паркер")
    await driver.findElement(By.name("search")).sendKeys(Key.ENTER)
    assert(await driver.findElement(By.css(".col-md-6 > span:nth-child(1)")).getText() == "9.99 р")
    await driver.findElement(By.linkText("Ручка Паркер")).click()
    assert(await driver.findElement(By.css(".col-md-6 > span:nth-child(1)")).getText() == "9.99 р")
    await driver.findElement(By.id("in_cart_link_29")).click()
    await driver.findElement(By.css("div:nth-child(2) > a:nth-child(1) > img")).click()
    assert(await driver.findElement(By.css(".col-md-3 > span:nth-child(1)")).getText() == "9.99 р")
    await driver.findElement(By.css(".mt-5")).click()
    assert(await driver.findElement(By.css(".col-md-2 > span:nth-child(3)")).getText() == "9.99 р")
    await driver.findElement(By.linkText("Удалить")).click()
    await driver.findElement(By.linkText("Выйти")).click()
    await driver.close()
  })
})
